httpserver/config/routes.rb
InterPerspective::Application.routes.draw do
  resources :topics do
    member do
      get 'swf'
      get 'current_room'
      get 'demo_room'
      get 'results'
      get 'log'
      post 'participate'
    end
    resources :rooms do
      member do
        get 'users'
        get 'messages'
        get 'finish_time'
        post 'speak'
        post 'express_attitude'
      end
    end
  end

  resources :users
  resources :user_sessions
  

  root :to => "topics#index"

end

httpserver/app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :rooms

  def active_rooms
    rooms.find(:all, :conditions => ['finish_at > ?', DateTime.current])
  end

  def open_rooms
    active_rooms.find_all { |room| room.open? }
  end

  def user_ids
    rooms.users_ids.inject(Array.new) { |array, ids| array | ids }
  end

  def select_room_for(user)
    # まだ話したことがない相手が一番多い部屋を選ぶ
    known_user_ids = user.known_user_ids(self)
    best_candidate = open_rooms.max_by{|room| (room.user_ids - known_user_ids).size }
    return (best_candidate && (best_candidate.user_ids - known_user_ids).size > 0) ? best_candidate : nil
  end
end

httpserver/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include PushUtils

  before_filter :require_user, :only => [ :participate ]

  def index
    @topics = Topic.find(:all)
  end

  def show
    @topic = Topic.find(params[:id])
    redirect_to swf_topic_url(@topic)
#    if current_user then
#      redirect_to swf_topic_url(@topic)
##      redirect_to [@topic, current_user.current_room_for(@topic)]
#    else
#      @participation = Participation.new
#    end
  end

  def swf
    @topic = Topic.find(params[:id])
    @flashVars = flash_vars(@topic)
    render :layout => false
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(params[:topic])

    if @topic.save then
      redirect_to @topic
    else
      render :action => 'new'
    end
  end

  ########################################################################
  # GET
  ########################################################################

  def current_room
    @topic = Topic.find(params[:id])
    @room = current_user.current_room_for(@topic)
    if @room then
      @participation = Participation.find_by_room_id_and_user_id(@room.id, current_user.id)
      @attitude = @participation.current_attitude
    end
  end

  def demo_room
    @topic = Topic.find(params[:id])
    @room = @topic.rooms.max_by{|r| rand() }
    @participation = @room.participations.find(:last)
    @attitude = @participation.current_attitude
    render 'current_room'
  end

  def results
    @topic = Topic.find(params[:id])
    @rooms = @topic.rooms.find(:all, :limit => 100)
  end

  def log
    @topic = Topic.find(params[:id])
  end

  ########################################################################
  # POST
  ########################################################################

  def participate
    @topic = Topic.find(params[:id])
    @room = current_user.current_room_for(@topic)

    unless @room then
      push_lines = []

      @topic.transaction do
        @room = @topic.select_room_for(current_user) || @topic.rooms.create
        if @room.users.size < @topic.min_roomsize then
          @room.finish_at = DateTime.current + @topic.roomtime.minutes
          @room.save
          push_lines << "#update_room_finish_time #{@room.id}" unless @room.users.empty?
        end
        @room.users << current_user
      end # end transaction

      @participation = Participation.find_by_room_id_and_user_id(@room.id, current_user.id)
      if @participation then
#        push_lines << process_participate_message(@participation)
#        push_lines << "#update_room_users #{@room.id}"
        push_lines << render_to_string(:partial => 'shared/participation', :locals => { :participation => @participation })
      end
      push_to_room(@room, push_lines)
    end
    
    respond_to do |format|
      format.html { redirect_to [@topic, @room] }
      format.xml { render :action => 'current_room' }
    end
  end


  protected

  def process_participate_message(p)
    message = Message.new do |m|
      m.participation = p
      m.body = "入室"
    end
    message.save
    render_to_string(:partial => 'shared/message', :locals => { :message => message })
  end

  def flash_vars(topic)
    @flashVars = {
      :authenticity_token => form_authenticity_token,
      :root_path => topic_url(topic),
      :title => @topic.title,
      :left => @topic.left,
      :right => @topic.right,
      :user_id => current_user ? current_user.id : -1,
      :host => Config[:public_host],
      :port => Config[:public_port]
    }
  end
end

httpserver/app/helpers/topics_helper.rb
module TopicsHelper
  def embed_flashvars(flashvars)
    @flashVars.collect{|k,v| k.to_s + ": '" + v.to_s + "'" }.join(', ')
  end
end

httpserver/app/views/topics/index.html.erb
<% @page_title = "InterPerspective" %>

<%= link_to "Create new topic", new_topic_url  %>

<h2>トピック一覧</h2>
<table>
  <tr><th>議題</th><th>議論の軸</th><th>１部屋の人数</th><th>１部屋の時間</th><th>ログ</th></tr>
<% @topics.each { |topic| -%>
  <tr>
    <td><%=  link_to topic.title, topic_url(topic) %></td>
    <td><%= topic.left %> 対 <%= topic.right %></td>
    <td><%= topic.min_roomsize %> ～ <%= topic.max_roomsize %>人</td>
    <td><%= topic.roomtime %> 分</td>
    <td><%=  link_to 'log', log_topic_url(topic) %></td>
  </tr>
<% } -%>
</table>

httpserver/app/views/topics/log.html.erb
<% @page_title = "議論の記録: #{@topic.title} #{@topic.left} 対 #{@topic.right}"  %>

<% @topic.rooms.each do |room| -%>
  <h2>部屋 <%= room.id %></h2>
  <% room.activities.each do |a| -%>
    <%= content_tag(:article, log_message(a)) %>
  <% end -%>
<% end -%>

httpserver/app/views/topics/new.html.erb
<% @page_title = "Create topic"  %>

<% form_for @topic do |f| -%>
  <!-- <%= f.error_messages %> TODO: learn how to validation in rails 3 -->
  トピック <%= f.text_field :title %> (<%= f.text_field :left %> vs. <%= f.text_field :right %>)<br/>
  １部屋の人数 <%= f.text_field :min_roomsize %> ～ <%= f.text_field :max_roomsize %> 人 <br/>
  １部屋の時間 <%= f.text_field :roomtime %> 分<br/>
  <%= f.submit %>
<% end -%>
  

httpserver/app/views/topics/results.xml.erb
<rooms>
  <% @rooms.each{|room|
    if room.users.size >= room.topic.min_roomsize -%>
  <room id="<%= room.id %>">
  <%=  render :partial => 'shared/participation', :collection => room.participations %>
  </room>
  <% end } -%>
</rooms>

httpserver/app/views/topics/show.html.erb
<% @page_title = @topic.title %>

<%= link_to 'トピック一覧', topics_url %>

<% if current_user then -%>
<%= button_to 'このトピックに参加する', participate_topic_url(@topic) %>
<% else -%>
<p>このトピックに参加するには <%= link_to 'ログイン', new_user_session_url %> する必要があります。</p>
<% end -%>

httpserver/app/views/topics/swf.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0014)about:internet -->
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <!--
  Smart developers always View Source.

  This application was built using Adobe Flex, an open source framework
  for building rich Internet applications that get delivered via the
  Flash Player or to desktops via Adobe AIR.

  Learn more about Flex at http://flex.org
  // -->
  <head>
    <title><%= @topic.title %> - InterPerspective</title>
    <meta name="google" value="notranslate" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- Include CSS to eliminate any default margins/padding and set the height of the html element and
		     the body element to 100%, because Firefox, or any Gecko based browser, interprets percentage as
			 the percentage of the height of its parent container, which has to be set explicitly.  Fix for
			 Firefox 3.6 focus border issues.  Initially, don't display flashContent div so it won't show
			 if JavaScript disabled.
		-->
    <style type="text/css" media="screen">
      html, body	{ height:100%; }
      body { margin:0; padding:0; overflow:auto; text-align:center;
             background-color: #ffffff; }
      object:focus { outline:none; }
      #flashContent { display:none; }
    </style>

    <!-- Enable Browser History by replacing useBrowserHistory tokens with two hyphens -->
    <!-- BEGIN Browser History required section -->
    <link rel="stylesheet" type="text/css" href="../history/history.css" />
    <script type="text/javascript" src="../history/history.js"></script>
    <!-- END Browser History required section -->

    <script type="text/javascript" src="../swfobject.js"></script>
    <script type="text/javascript">
      <!-- For version detection, set to min. required Flash Player version, or 0 (or 0.0.0), for no version detection. -->
      var swfVersionStr = "10.0.0";
      <!-- To use express install, set to playerProductInstall.swf, otherwise the empty string. -->
      var xiSwfUrlStr = "playerProductInstall.swf";
      var flashvars = { <%= embed_flashvars @flashVars %> };
      var params = {};
      params.quality = "high";
      params.bgcolor = "#ffffff";
      params.allowscriptaccess = "sameDomain";
      params.allowfullscreen = "true";
      var attributes = {};
      attributes.id = "InterPerspective";
      attributes.name = "InterPerspective";
      attributes.align = "middle";
      swfobject.embedSWF(
      "../Main.swf", "flashContent",
      "100%", "100%",
      swfVersionStr, xiSwfUrlStr,
      flashvars, params, attributes);
      <!-- JavaScript enabled so display the flashContent div in case it is not replaced with a swf object. -->
      swfobject.createCSS("#flashContent", "display:block;text-align:left;");
    </script>
  </head>
  <body>
    <!-- SWFObject's dynamic embed method replaces this alternative HTML content with Flash content when enough
			 JavaScript and Flash plug-in support is available. The div is initially hidden so that it doesn't show
			 when JavaScript is disabled.
		-->
    <div id="flashContent">
      <p>
	        	To view this page ensure that Adobe Flash Player version
				10.0.0 or greater is installed.
      </p>
      <script type="text/javascript">
        var pageHost = ((document.location.protocol == "https:") ? "https://" :	"http://");
        document.write("<a href='http://www.adobe.com/go/getflashplayer'><img src='"
          + pageHost + "www.adobe.com/images/shared/download_buttons/get_flash_player.gif' alt='Get Adobe Flash player' /></a>" );
      </script>
    </div>

    <noscript>
      <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="100%" height="100%" id="InterPerspective">
        <param name="movie" value="../Main.swf" />
        <param name="quality" value="high" />
        <param name="bgcolor" value="#ffffff" />
        <param name="allowScriptAccess" value="sameDomain" />
        <param name="allowFullScreen" value="true" />
        <!--[if !IE]>-->
        <object type="application/x-shockwave-flash" data="../InterPerspective.swf" width="100%" height="100%">
          <param name="quality" value="high" />
          <param name="bgcolor" value="#ffffff" />
          <param name="allowScriptAccess" value="sameDomain" />
          <param name="allowFullScreen" value="true" />
          <!--<![endif]-->
          <!--[if gte IE 6]>-->
          <p>
                		Either scripts and active content are not permitted to run or Adobe Flash Player version
                		10.0.0 or greater is not installed.
          </p>
          <!--<![endif]-->
          <a href="http://www.adobe.com/go/getflashplayer">
            <img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash Player" />
          </a>
          <!--[if !IE]>-->
        </object>
        <!--<![endif]-->
      </object>
    </noscript>
  </body>
</html>