httpserver/config/routes.rb
InterPerspective::Application.routes.draw do
  resources :topics do
    member do
      get 'swf'
      get 'current_room'
      get 'demo_room'
      get 'results'
      get 'log'
      post 'participate'
    end
    resources :rooms do
      member do
        get 'users'
        get 'messages'
        get 'finish_time'
        post 'speak'
        post 'express_attitude'
      end
    end
  end

  resources :users
  resources :user_sessions
  

  root :to => "topics#index"

end

httpserver/app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end

  def persisted?
    false
  end
end

httpserver/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])

    if @user_session.save then
      redirect_back_or_default :root, :notice => 'ログインしました'
    else
      render :action => 'new', :notice => 'ログインに失敗しました'
    end
  end

  def destroy
    current_user_session.destroy
    redirect_back_or_default :root, :notice => 'ログアウトしました'
  end
end

httpserver/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

httpserver/app/views/user_sessions/new.html.erb
<% @page_title = 'ログイン' %>

<p>※初めて利用する方は先に <%= link_to 'ユーザ登録', new_user_url %> を行う必要があります。</p>

<%= form_for @user_session do |f| %>



  <div class="field">
    <%= f.label :login %>（チャットで使用する名前）<br />
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit 'ログイン' %>
  </div>
<% end %>